web:
  build: .
  command: php -S 0.0.0.0:8000 -t /mundi-challenge
  ports:
    - "80:8000"
  links:
    - db
  volumes:
    - .:/mundi-challenge
db:
  image: orchardup/mysql
  environment:
    MYSQL_DATABASE: mundi-challenge
